INSERT INTO members (name) VALUES ('Janmara Rocha Sousa');
INSERT INTO members (name) VALUES ('Paloma Cristina De Oliveira Pinheiro');
INSERT INTO members (name) VALUES ('Elaine Bloise');
INSERT INTO members (name) VALUES ('Gerson Barros');
INSERT INTO members (name) VALUES ('Aline Scheibler');
INSERT INTO members (name) VALUES ('Eliane Cristina Secco');
INSERT INTO members (name) VALUES ('Haydée Silveira');
INSERT INTO members (name) VALUES ('Ana Lúcia Fernandez André Riboli');
INSERT INTO members (name) VALUES ('Lucília Gonçalves');
INSERT INTO members (name) VALUES ('Maria De Fátima Machado De Albuquerque');
INSERT INTO members (name) VALUES ('Ione Pereira De Araújo');
INSERT INTO members (name) VALUES ('Maciel Fernandes Da Silva');
INSERT INTO members (name) VALUES ('Ivone Haese');
INSERT INTO members (name) VALUES ('Lara Elis Delfino Rosa');
INSERT INTO members (name) VALUES ('Thaís Souza Alves');
INSERT INTO members (name) VALUES ('Solange Chadi');
INSERT INTO members (name) VALUES ('Victor Paulo Nascimento Martins');
INSERT INTO members (name) VALUES ('Cristiane Lima');
INSERT INTO members (name) VALUES ('Maria Beatriz Aguiar De Oliveira Takashi');
INSERT INTO members (name) VALUES ('Aline Aparecida Soares Ferasso');
INSERT INTO members (name) VALUES ('Pâmela Lino Costa');
INSERT INTO members (name) VALUES ('Samara Chaves');
INSERT INTO members (name) VALUES ('Leandra De Aquino Paschoal');
INSERT INTO members (name) VALUES ('Anne Kelly Azevedo Kil');
INSERT INTO members (name) VALUES ('Danielle Alves Barreto');
INSERT INTO members (name) VALUES ('Raimundo Edson Lima De Medeiros');
INSERT INTO members (name) VALUES ('Vera Lucia Noronha Ferreira');
INSERT INTO members (name) VALUES ('Juliete Do Nascimento Costa');
INSERT INTO members (name) VALUES ('Dyana Batista Da Silva');
INSERT INTO members (name) VALUES ('Bruna Looze Laureano');
INSERT INTO members (name) VALUES ('Modesto Costa');
INSERT INTO members (name) VALUES ('Stefanie Hoeger');
INSERT INTO members (name) VALUES ('Maria Aparecida Faipó');
INSERT INTO members (name) VALUES ('Elizabeth Bensi');
INSERT INTO members (name) VALUES ('Karen Caroline Borges Carmelo');
INSERT INTO members (name) VALUES ('Vanessa Ribeiro Barbosa');
INSERT INTO members (name) VALUES ('Marilin Aparecida Ferraz Martinez');
INSERT INTO members (name) VALUES ('Caio Pereira Silva');
INSERT INTO members (name) VALUES ('Jeferson Valim');
INSERT INTO members (name) VALUES ('Vani Lucia Pereira Homem');
INSERT INTO members (name) VALUES ('Caio Borges Neves');
INSERT INTO members (name) VALUES ('Cristiane Lombardi');
INSERT INTO members (name) VALUES ('Maria Helena Nóbrega Caires');
INSERT INTO members (name) VALUES ('Vinícius Lopes Saporito Da Silva');
INSERT INTO members (name) VALUES ('Maria Aparecida Goncalves Braga');
INSERT INTO members (name) VALUES ('Soraia Ribovski');
INSERT INTO members (name) VALUES ('Filipe Serafim Paula');
INSERT INTO members (name) VALUES ('Leonardo Yozo Kono');
INSERT INTO members (name) VALUES ('Eliane Moreira De Castro');
INSERT INTO members (name) VALUES ('Simara Silva');
INSERT INTO members (name) VALUES ('Ana Luiza Quedevez');
INSERT INTO members (name) VALUES ('Fernanda Russo');
INSERT INTO members (name) VALUES ('Gisele Zlotowski Giordano');
INSERT INTO members (name) VALUES ('Adriana Poggio De Oliveira');
INSERT INTO members (name) VALUES ('José Vitor Blanco');
INSERT INTO members (name) VALUES ('Paula Maria Anjos Almeida');
INSERT INTO members (name) VALUES ('Cristina Maria Sereno Augusto De Albuquerque');
INSERT INTO members (name) VALUES ('Silvania Capua Carvalho');
INSERT INTO members (name) VALUES ('Adriana Santana Machado');
INSERT INTO members (name) VALUES ('Camila Aguiar Mourão');
INSERT INTO members (name) VALUES ('Fredy Costa Guerra');
INSERT INTO members (name) VALUES ('Iana Lopes Bicalho');
INSERT INTO members (name) VALUES ('Giovani Milanez Espindola');
INSERT INTO members (name) VALUES ('Lidia Vieira Nery');
INSERT INTO members (name) VALUES ('Carina Casanova Pires');
INSERT INTO members (name) VALUES ('Kiki A. Barbosa');
INSERT INTO members (name) VALUES ('Raquel Vidart');
INSERT INTO members (name) VALUES ('Cristina Martínez Rubiño');
INSERT INTO members (name) VALUES ('Hélio Gabriel');
INSERT INTO members (name) VALUES ('Patrícia Cintra Leite');
INSERT INTO members (name) VALUES ('Paulo Cesar Pereira');
INSERT INTO members (name) VALUES ('Janaina Bonini Dos Reis Butcovsky');
INSERT INTO members (name) VALUES ('Rafael Moury Fernandes Leite De Oliveira');
INSERT INTO members (name) VALUES ('Rossana Alves Dos Santos');
INSERT INTO members (name) VALUES ('Isabel Paulo');
INSERT INTO members (name) VALUES ('Tania Cristina Amorim Gutierrez');
INSERT INTO members (name) VALUES ('Diego Castro Alves');
INSERT INTO members (name) VALUES ('Camila Rosa de Moraes');
INSERT INTO members (name) VALUES ('Aparecida de Oliveira Azevedo');
INSERT INTO members (name) VALUES ('Natallyanea Silva Bezerra');
INSERT INTO members (name) VALUES ('Roselaine Trentin Maciel');
INSERT INTO members (name) VALUES ('Alessandra Cristina da Silva Leal');
INSERT INTO members (name) VALUES ('Débora Assing Francioni de Campos');
INSERT INTO members (name) VALUES ('Gleid Nara Lodi Do Lago');
INSERT INTO members (name) VALUES ('Neila Nogueira');
INSERT INTO members (name) VALUES ('Renilda Rizzatti Celeprin');
INSERT INTO members (name) VALUES ('Katia Silene Anacleto Jacobete');
INSERT INTO members (name) VALUES ('Síria');
INSERT INTO members (name) VALUES ('Shuman');
INSERT INTO members (name) VALUES ('Sans Nom');
INSERT INTO members (name) VALUES ('Dantas');
INSERT INTO members (name) VALUES ('João');
INSERT INTO members (name) VALUES ('Kao Lee');
