CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "member" bool,
  "admin" bool,
  "avatar" varchar,
  "created" timestamp NOT NULL
);

CREATE TABLE "uti_patients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "name" varchar NOT NULL,
  "birthday" date,
  "description" varchar,
  "created" date,
  "deleted" bool
);

CREATE TABLE "uti_queue" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_uti" int NOT NULL,
  "joined" timestamp,
  "position" int NOT NULL
);

CREATE TABLE "sessions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "title" varchar NOT NULL,
  "desc" varchar,
  "place" varchar NOT NULL,
  "place_img" bytea,
  "done" bool,
  "date" timestamp NOT NULL
);


CREATE TABLE "members_session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_member" int NOT NULL,
  "id_session" int NOT NULL
);

CREATE TABLE "uti_session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_uti" int NOT NULL,
  "id_session" int NOT NULL
);

CREATE TABLE "members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "uti_patients" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "uti_queue" ADD FOREIGN KEY ("id_uti") REFERENCES "uti_patients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "sessions" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "members_session" ADD FOREIGN KEY ("id_member") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "members_session" ADD FOREIGN KEY ("id_session") REFERENCES "sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "uti_session" ADD FOREIGN KEY ("id_uti") REFERENCES "uti_patients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "uti_session" ADD FOREIGN KEY ("id_session") REFERENCES "sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

