package migration

import (
	"database/sql"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Migration represents a database migration
type Migration struct {
	Version int
	Name    string
	SQL     string
}

// Migrator handles database migrations
type Migrator struct {
	db             *sql.DB
	migrationsPath string
	seedPath       string
}

// NewMigrator creates a new migrator instance
func NewMigrator(db *sql.DB, migrationsPath, seedPath string) *Migrator {
	return &Migrator{
		db:             db,
		migrationsPath: migrationsPath,
		seedPath:       seedPath,
	}
}

// ensureMigrationsTable creates the migrations tracking table if it doesn't exist
func (m *Migrator) ensureMigrationsTable() error {
	query := `
		CREATE TABLE IF NOT EXISTS schema_migrations (
			version INT PRIMARY KEY,
			name VARCHAR(255) NOT NULL,
			applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		)
	`
	_, err := m.db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to create migrations table: %w", err)
	}
	return nil
}

// ensureSeedsTable creates the seeds tracking table if it doesn't exist
func (m *Migrator) ensureSeedsTable() error {
	query := `
		CREATE TABLE IF NOT EXISTS schema_seeds (
			id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(255) NOT NULL,
			applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		)
	`
	_, err := m.db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to create seeds table: %w", err)
	}
	return nil
}

// getAppliedMigrations returns a map of applied migration versions
func (m *Migrator) getAppliedMigrations() (map[int]bool, error) {
	rows, err := m.db.Query("SELECT version FROM schema_migrations")
	if err != nil {
		return nil, fmt.Errorf("failed to query applied migrations: %w", err)
	}
	defer rows.Close()

	applied := make(map[int]bool)
	for rows.Next() {
		var version int
		if err := rows.Scan(&version); err != nil {
			return nil, fmt.Errorf("failed to scan migration version: %w", err)
		}
		applied[version] = true
	}

	return applied, nil
}

// isSeedApplied checks if a seed has already been applied
func (m *Migrator) isSeedApplied(seedName string) (bool, error) {
	var count int
	err := m.db.QueryRow("SELECT COUNT(*) FROM schema_seeds WHERE name = $1", seedName).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("failed to check if seed is applied: %w", err)
	}
	return count > 0, nil
}

// loadMigrations loads all migration files from the migrations directory
func (m *Migrator) loadMigrations() ([]Migration, error) {
	files, err := ioutil.ReadDir(m.migrationsPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read migrations directory: %w", err)
	}

	var migrations []Migration
	for _, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".sql") {
			continue
		}

		// Parse filename format: 001_migration_name.sql
		parts := strings.SplitN(file.Name(), "_", 2)
		if len(parts) != 2 {
			log.Printf("Warning: skipping invalid migration filename: %s", file.Name())
			continue
		}

		var version int
		if _, err := fmt.Sscanf(parts[0], "%d", &version); err != nil {
			log.Printf("Warning: skipping invalid migration version in filename: %s", file.Name())
			continue
		}

		name := strings.TrimSuffix(parts[1], ".sql")

		// Read SQL content
		content, err := ioutil.ReadFile(filepath.Join(m.migrationsPath, file.Name()))
		if err != nil {
			return nil, fmt.Errorf("failed to read migration file %s: %w", file.Name(), err)
		}

		migrations = append(migrations, Migration{
			Version: version,
			Name:    name,
			SQL:     string(content),
		})
	}

	// Sort migrations by version
	sort.Slice(migrations, func(i, j int) bool {
		return migrations[i].Version < migrations[j].Version
	})

	return migrations, nil
}

// applyMigration applies a single migration
func (m *Migrator) applyMigration(migration Migration) error {
	tx, err := m.db.Begin()
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	// Execute migration SQL
	if _, err := tx.Exec(migration.SQL); err != nil {
		return fmt.Errorf("failed to execute migration %d (%s): %w", migration.Version, migration.Name, err)
	}

	// Record migration
	if _, err := tx.Exec(
		"INSERT INTO schema_migrations (version, name) VALUES ($1, $2)",
		migration.Version,
		migration.Name,
	); err != nil {
		return fmt.Errorf("failed to record migration %d: %w", migration.Version, err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("failed to commit migration %d: %w", migration.Version, err)
	}

	log.Printf("Applied migration %03d: %s", migration.Version, migration.Name)
	return nil
}

// Run executes all pending migrations
func (m *Migrator) Run() error {
	log.Println("Starting database migrations...")

	// Ensure migrations table exists
	if err := m.ensureMigrationsTable(); err != nil {
		return err
	}

	// Get applied migrations
	applied, err := m.getAppliedMigrations()
	if err != nil {
		return err
	}

	// Load migration files
	migrations, err := m.loadMigrations()
	if err != nil {
		return err
	}

	// Apply pending migrations
	pendingCount := 0
	for _, migration := range migrations {
		if !applied[migration.Version] {
			if err := m.applyMigration(migration); err != nil {
				return err
			}
			pendingCount++
		}
	}

	if pendingCount == 0 {
		log.Println("No pending migrations")
	} else {
		log.Printf("Applied %d migration(s)", pendingCount)
	}

	return nil
}

// RunSeed runs the seed file if it hasn't been run before
func (m *Migrator) RunSeed() error {
	log.Println("Checking database seeds...")

	// Ensure seeds table exists
	if err := m.ensureSeedsTable(); err != nil {
		return err
	}

	// Check if seed file exists
	if _, err := os.Stat(m.seedPath); os.IsNotExist(err) {
		log.Println("No seed file found, skipping seeding")
		return nil
	}

	// Get seed filename
	seedName := filepath.Base(m.seedPath)

	// Check if seed has already been applied
	applied, err := m.isSeedApplied(seedName)
	if err != nil {
		return err
	}

	if applied {
		log.Println("Seeds already applied, skipping")
		return nil
	}

	// Read seed file
	content, err := ioutil.ReadFile(m.seedPath)
	if err != nil {
		return fmt.Errorf("failed to read seed file: %w", err)
	}

	// Begin transaction
	tx, err := m.db.Begin()
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	// Execute seed SQL
	if _, err := tx.Exec(string(content)); err != nil {
		return fmt.Errorf("failed to execute seed: %w", err)
	}

	// Record seed
	if _, err := tx.Exec(
		"INSERT INTO schema_seeds (name) VALUES ($1)",
		seedName,
	); err != nil {
		return fmt.Errorf("failed to record seed: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("failed to commit seed: %w", err)
	}

	log.Printf("Applied seed: %s", seedName)
	return nil
}
